//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basketballMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roster
    {
        public int RosterID { get; set; }
        public int SeasonTeamID { get; set; }
        public int PlayerID { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual SeasonTeam SeasonTeam { get; set; }
    }
}
