//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basketballMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int PlayerID { get; set; }
        public int GameID { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> Rebounds { get; set; }
        public Nullable<int> Assists { get; set; }
        public Nullable<int> Steals { get; set; }
        public Nullable<int> Blocks { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
